### ISSUE TITLE
Verificação de acesso aos componentes do projeto

### ISSUE THREAD

**Issue by hugouraga** [hugouraga/Iggle#1]
<b>Objetivo</b>: Criar intimidade com a plataforma.
<b>Teste</b>: Todos os membros do grupo devem comentar algo.

**Comment by hugouraga** [comment]
teste de verificação

**Comment by myllenaalves** [comment]
Acesso verificado

**Comment by jussararodrigues** [comment]
Acesso verificado.

**Comment by MyllenaAlmeida** [comment]
Verificado.

**Comment by jslvdan** [comment]
verificado
