### ISSUE TITLE
Feedback IT0

### ISSUE THREAD

**Issue by aacgn** [hugouraga/Iggle#37]
Oi pessoal,

Dei uma olhada no projeto de vocês pegando todos os commits até a data de 25/03 para estabelecer os scores da iteração 0. As notas estão disponíveis na [planilha](https://docs.google.com/spreadsheets/d/1GkFDV3nYW0T1pPfywhpRdSFeazGG40xy3UQm50Ps2rU/edit#gid=512779380), mas vou dar um pequeno resumo.

Parabéns, a maioria das competências recebeu nota máxima. Apenas uma que não conseguiu atender todos os pre-requisitos: Histórias de usuários [HU].

Durante a descrição das história de usuário foi observado que algumas delas não seguem totalmente o modelo "quem... o quê... por quê", faltando em uma grande quantidade o "por quê". Exemplo: "Como usuário do Iggle quero visualizar a agenda de todos os profissionais.", faltou informar por que ele quer ter essa visualização, o que ele irá fazer com ela.

Mas foi só isso, novamente meus parabéns. o/

**Comment by jslvdan** [comment]
Obrigado pelo feedback, Antonio.
