### ISSUE TITLE
Feedback da IT3 ~ Cadastrar histórias no Github

### ISSUE THREAD

**Issue by ricardoebbers** [hugouraga/Iggle#38]
# Feedback da IT3 ~ Cadastrar histórias no Github

Opa galera, beleza?

Passando aqui para deixar o feedback da entrega das histórias no Github da IT3.
Para esse feedback estou levando em conta as issues #13, #17 e #26 ([Search query](https://github.com/hugouraga/Iggle/issues?utf8=%E2%9C%93&q=is%3Aissue+closed%3A2019-05-09..2019-05-22)), que foram fechadas entre 09/05 e 22/05, e as demais fechadas do [milestone da IT3](https://github.com/hugouraga/Iggle/milestone/4?closed=1).

## TL:DR
| Prazo | Critério | Avaliação | Nota |
| - | - | - | - |
22/05 | Cadastrar histórias no Github | All good! :) | 10 |

## Drilldown

- [x] Formatadas no padrão Connextra;  
- [x] Histórias bem descritas, com diversos cenários claramente testáveis;  
- [x] Uso de labels, milestones e projects;  
- [x] Todas as issues com assignees.

**Comment by jslvdan** [comment]
Obrigado pero feedback, Ricardo!
