### ISSUE TITLE
Feedback Postmortem - Iteração 1

### ISSUE THREAD

**Issue by mateuscardosogs** [hugouraga/Iggle#58]
Iae pessoal, vou dar o feedback do postmortem da iteração 1 para vocês.

## Postmortem:
<ul>
  <li>Período -> OK</li>
  <li>O que estava planejado -> OK</li>
  <li>O que foi feito -> OK</li>
  <li>O que não foi feito -> OK</li>
  <li>O que está planejado pra próxima iteração -> OK</li>
  <li>Lições aprendidas -> OK</li>
  <li>Formato Markdown -> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------

**Comment by jslvdan** [comment]
Obrigado pelo feedback, Mateus!
