### ISSUE TITLE
Feedback IT3 ~ Testes TDD e BDD

### ISSUE THREAD

**Issue by aacgn** [hugouraga/Iggle#61]
Oi, pessoal. 
Segue o feedback da iteração 3 relacionado aos testes TDD e BDD.

Prazo | Critério | Avaliação | Nota
-- | -- | -- | --
22/05 | Testes | Os testes parecem estar correto. Distingue caminhos tristes e felizes, executa as features principais implementadas, porém ainda não cobre as principais features que estarão a ser implementadas (mesmo que estivem comentadas). Como o objetivo do projeto é que seja feita uma perspectiva de desenvolvimento TDD (desenvolver testes primeiro e depois as features) vocês não irão obter nota máxima. Mas foi um ótimo trabalho.| 8.00

**Comment by jslvdan** [comment]
Obrigado pelo feedback, Antonio!
